### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by dodek22** [HexagonMC/BungeeCord#145]
09:44:22 [SEVERE] maj 07, 2017 9:44:22 AM io.netty.util.concurrent.AbstractEventExecutor safeExecute
WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@dcf79db
java.lang.IllegalStateException: Cancelled ServerConnectEvent with no server or disconnect.
    at net.md_5.bungee.UserConnection.connect(UserConnection.java:262)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:524)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:748)
 

what is this?

**Comment by ghacproductions** [comment]
Duplicate #144.
