### ISSUE TITLE
Disconnect/Crash with forge 1.7.10

### ISSUE THREAD

**Issue by Maymity** [HexagonMC/BungeeCord#164]
### What Hexacord version are you using? Post the output of /bungee
 This server is running Hexacord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:53fda71:154 by md_5
Protocol support for 1.7.x by Zartec, ghac and I9hdkill

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
SkinRestorer Latest version

### How can we reproduce the error/bug? 
When i try to join in Faction server from lobby

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
NativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1

### In addidtion to that, please explain your issue as detailed as possible.
This problem is with 1.7.10 forge

**Comment by spannerman79** [comment]
Dupe #152

**Comment by Maymity** [comment]
Sorry i don't understand. What is the solution?

**Comment by Maymity** [comment]
(My server is 1.7-1.8)

**Comment by popcorn9499** [comment]
The temporary solution is to use release 140 or lower. Anything above that adds 1.12 support which seems to break some things with forge. Does this help Maymity?

**Comment by Maymity** [comment]
Man i test it but now nothing(Relase 140).
My game crashed with this error: 
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 27/06/17 18.28
Description: Unexpected error

java.lang.IllegalArgumentException: Could not get provider type for dimension 12, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:65)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:871)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:65)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:871)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Maymity'/0, l='MpServer', x=-519,52, y=102,39, z=-280,60]]
	Chunk stats: MultiplayerChunkCache: 20, 20
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-520,101,-218), Chunk: (at 8,6,6 in -33,-14; contains blocks -528,0,-224 to -513,255,-209), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 18283109 game time, 680016662 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 44 total; [EntityClientPlayerMP['Maymity'/0, l='MpServer', x=-519,52, y=102,39, z=-280,60], EntityVillager['§e§lSell'/321, l='MpServer', x=-540,00, y=98,00, z=-298,22], EntityHorse['§7§m§l{----------}'/390, l='MpServer', x=-514,53, y=152,80, z=-279,41], EntityWitherSkull['entity.WitherSkull.name'/391, l='MpServer', x=-514,53, y=152,56, z=-279,41], EntityHorse['§e§lFree'/392, l='MpServer', x=-514,53, y=152,55, z=-279,41], EntityWitherSkull['entity.WitherSkull.name'/393, l='MpServer', x=-514,53, y=152,31, z=-279,41], EntityHorse['§7§m§l{----------}'/394, l='MpServer', x=-514,53, y=152,30, z=-279,41], EntityWitherSkull['entity.WitherSkull.name'/395, l='MpServer', x=-514,53, y=152,06, z=-279,41], EntityHorse['§7§m§l{----------}'/340, l='MpServer', x=-486,56, y=151,47, z=-270,38], EntityWitherSkull['entity.WitherSkull.name'/341, l='MpServer', x=-486,56, y=151,47, z=-270,41], EntityHorse['§e§lEnchant'/342, l='MpServer', x=-486,56, y=151,22, z=-270,38], EntityWitherSkull['entity.WitherSkull.name'/343, l='MpServer', x=-486,56, y=151,22, z=-270,41], EntityHorse['§7§m§l{----------}'/344, l='MpServer', x=-486,56, y=150,97, z=-270,38], EntityWitherSkull['entity.WitherSkull.name'/345, l='MpServer', x=-486,56, y=150,97, z=-270,41], EntitySpider['Ragno'/219, l='MpServer', x=-543,50, y=54,00, z=-277,91], EntitySpider['Ragno'/220, l='MpServer', x=-535,72, y=53,00, z=-276,88], EntitySkeleton['Scheletro'/221, l='MpServer', x=-540,88, y=55,00, z=-278,69], EntitySkeleton['Scheletro'/222, l='MpServer', x=-535,91, y=62,00, z=-257,56], EntitySpider['Ragno'/223, l='MpServer', x=-535,86, y=53,00, z=-271,95], EntitySpider['Ragno'/224, l='MpServer', x=-530,84, y=77,00, z=-267,53], EntityHorse['§7§m§l{----------}'/352, l='MpServer', x=-527,28, y=152,70, z=-295,00], EntitySpider['Ragno'/225, l='MpServer', x=-528,88, y=75,00, z=-260,28], EntityWitherSkull['entity.WitherSkull.name'/353, l='MpServer', x=-527,28, y=152,47, z=-295,00], EntityHorse['§e§lShop'/354, l='MpServer', x=-527,28, y=152,45, z=-295,00], EntityWitherSkull['entity.WitherSkull.name'/355, l='MpServer', x=-527,28, y=152,22, z=-295,00], EntityHorse['§7§m§l{----------}'/356, l='MpServer', x=-527,28, y=152,20, z=-295,00], EntitySkeleton['Scheletro'/229, l='MpServer', x=-517,53, y=97,50, z=-281,72], EntityWitherSkull['entity.WitherSkull.name'/357, l='MpServer', x=-527,28, y=151,97, z=-295,00], EntityZombie['Zombi'/230, l='MpServer', x=-524,94, y=63,00, z=-256,53], EntitySkeleton['Scheletro'/231, l='MpServer', x=-520,53, y=66,00, z=-265,13], EntityZombie['Zombi'/232, l='MpServer', x=-524,00, y=78,00, z=-264,56], EntityZombie['Zombi'/235, l='MpServer', x=-505,88, y=114,00, z=-257,53], EntityVillager['§e§lShop'/303, l='MpServer', x=-539,34, y=98,00, z=-295,00], EntityHorse['§bIl processo per divenire §cYou§fTuber'/370, l='MpServer', x=-500,31, y=143,30, z=-296,28], EntityWitherSkull['entity.WitherSkull.name'/371, l='MpServer', x=-500,31, y=143,06, z=-296,28], EntityVillager['§4§lCandidati'/308, l='MpServer', x=-512,50, y=87,00, z=-296,50], EntityHorse['§be' completamente §c§lAUTOMATIZZATO!'/372, l='MpServer', x=-500,31, y=143,05, z=-296,28], EntityVillager['§4§lYoutuber'/309, l='MpServer', x=-505,50, y=86,00, z=-292,50], EntityWitherSkull['entity.WitherSkull.name'/373, l='MpServer', x=-500,31, y=142,81, z=-296,28], EntityHorse['§cClicca §asull'NPC dietro di te'/374, l='MpServer', x=-500,31, y=142,80, z=-296,28], EntityVillager['§c§lMod'/310, l='MpServer', x=-494,47, y=96,00, z=-241,34], EntityWitherSkull['entity.WitherSkull.name'/375, l='MpServer', x=-500,31, y=142,56, z=-296,28], EntityVillager['§5§lVip'/312, l='MpServer', x=-526,31, y=96,00, z=-282,53], EntityVillager['§4§lFree'/318, l='MpServer', x=-514,44, y=97,00, z=-283,72]]
	Retry entities: 0 total; []
	Server brand: Infinity 1.0-Stable (git:BungeeCord-Bootstrap:1.11-SNAPSHOT:faccbda:140) <- PaperSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 220488728 bytes (210 MB) / 369270784 bytes (352 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJA	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
	UCHIJA	DirectionHUD{1.24} [DirectionHUD] ([1.7.10]DirectionHUD-client-1.24.jar) 
	UCHIJA	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) 
	UCHIJA	cpsmod{1.0} [CPSMod] (CPSMod 1.1.jar) 
	UCHIJA	keystrokesmod{0.1} [KeystrokesMod] (KeystrokesMod.jar) 
	UCHIJA	satdismodid{1.0} [SaturationDisplay] (SaturationDisplay-1.7.2-2.0.jar) 
	UCHIJA	{1.0} [] (TcpNoDelayMod-1.0.jar) 
	UCHIJA	ToggleSneak{3.0.3} [ToggleSneak] (ToggleSneak-(1.7.10)-v3.0.5 (iShadowsClient).jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [§8! §3iShadows §832x §7Private.zip]
	Current Language: Italiano (Italia)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by popcorn9499** [comment]
could u try this without the bungee to see if it solves that issue? becuz that looks like a world or server configuration error and I'd be happy to help with that i just need you to test without that.
btw what modpack are we looking at?

**Comment by Maymity** [comment]
I don't use modpack but PaperSpigot 1.7.10 Protocol Hack but forge is important for pvp mod

**Comment by Maymity** [comment]
I can connect to the hub but not to the factions

**Comment by Maymity** [comment]
i found the problem: The problem is my spawn world. How i fix it?

**Comment by popcorn9499** [comment]
U need to give me a bit more info. What server plugins r u using. and how is Ur world configured. How many world's exist and stuff.

**Comment by popcorn9499** [comment]
I may have an idea but I need to know if Ur spawn world is a Bukit plugin world

**Comment by popcorn9499** [comment]
U see I previously encountered a error a while back with plugins creating world's. The solution was to have u login on a world forge had created then after the forge handshake and stuff force the player to the spawn world. That worked fairly well. So on logout the player went to the overworld or something and on login got teleported to the spawn world

**Comment by Shoxxo** [comment]
12:16:13 [INFORMATION] [ChunkBuster2K7] <-> ServerConnector [ftb] has connected
12:16:13 [SCHWERWIEGEND] [ChunkBuster2K7] <-> DownstreamBridge <-> [ftb] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException
12:16:13 [INFORMATION] [ChunkBuster2K7] <-> DownstreamBridge <-> [ftb] has disconnected
12:16:13 [INFORMATION] [ChunkBuster2K7] <-> ServerConnector [lobby] has connected
12:16:13 [INFORMATION] [ChunkBuster2K7] <-> DownstreamBridge <-> [lobby] has disconnected

**Comment by i9hdkill** [comment]
This issue was fixed lately
