### ISSUE TITLE
Overlord incompatibility: network connection lost with "Unknown meta type 14"

### ISSUE THREAD

**Issue by LemADEC** [HexagonMC/BungeeCord#200]
### What Hexacord version are you using? Post the output of /bungee
```
version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:b5f17e7:190 by md_5
Protocol support for 1.7.x by Zartec, ghac and I9hdkill
```

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
AlwaysOnline-6.1.jar
BungeeRTK-0.2.0.jar
CommandControl-1.1.jar
EMPBungee-beta2017-03-30.jar
LuckPerms-Bungee-4.1.31build582.jar
movemenow-1.2-17.jar
nuvotifier-universal-2.3.5.jar
SlingShot-1.0.0.jar
VersionConnector-1.4.jar

### How can we reproduce the error/bug? 
Have a dedicated 1.10.2 server running Overlord-1.10.2-2.3.7.jar
Spawn a skeleton warrior from the mod (or use vanilla one + weakness potion + god apple and wait 20mn)
Try to reconnect or reload the chunk containing said skeleton will result in player getting disconnected.
According to Bungee logs, an "Unknown meta type 14" exception is raised.

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
```
20:10:17 [INFO] [/xxxx:61745] <-> InitialHandler has connected
20:10:18 [INFO] [VersionConnector] LemADEC's version: 210/MINECRAFT_1_10/forge: true
20:10:18 [INFO] [LemADEC] <-> ServerConnector [magewars] has connected
20:10:21 [INFO] [VersionConnector] LemADEC's version: 210/MINECRAFT_1_10/forge: true
20:10:21 [SEVERE] [LemADEC] <-> DownstreamBridge <-> [magewars] - encountered exception
java.lang.IllegalArgumentException: Unknown meta type 14
    at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:204)
    at net.md_5.bungee.entitymap.EntityMap_1_10.rewriteClientbound(EntityMap_1_10.java:152)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:100)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at java.lang.Thread.run(Thread.java:748)
20:10:21 [INFO] [LemADEC] <-> DownstreamBridge <-> [xxx] has disconnected
20:10:21 [INFO] [LemADEC] <-> ServerConnector [hub] has connected
```

### In addidtion to that, please explain your issue as detailed as possible.
Directly connecting to the server without bungee will not reproduce the issue.

**Comment by LemADEC** [comment]
Dup of #207
