### ISSUE TITLE
Command input doesn't work since last update

### ISSUE THREAD

**Issue by NathanFallet** [HexagonMC/BungeeCord#245]
Each time I start my server I see this error in logs:

```
19:18:20 [GRAVE] Exception in thread "main" 
19:18:20 [GRAVE] java.io.IOException: Ressource temporairement non disponible
19:18:20 [GRAVE] 	at java.io.FileInputStream.read0(Native Method)
19:18:20 [GRAVE] 	at java.io.FileInputStream.read(FileInputStream.java:207)
19:18:20 [GRAVE] 	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169)
19:18:20 [GRAVE] 	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137)
19:18:20 [GRAVE] 	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246)
19:18:20 [GRAVE] 	at jline.internal.InputStreamReader.read(InputStreamReader.java:261)
19:18:20 [GRAVE] 	at jline.internal.InputStreamReader.read(InputStreamReader.java:198)
19:18:20 [GRAVE] 	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145)
19:18:20 [GRAVE] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2349)
19:18:20 [GRAVE] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
19:18:20 [GRAVE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:117)
19:18:20 [GRAVE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

And since I have this error, I'm unable to write commands in the console. Is it related? Is it a change in a recent update?

I'm running the latest build (v225) on
```
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-45-generic x86_64)

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

I still attentive to any question.

**Comment by NathanFallet** [comment]
Well it is now working again, but I don't know why
