### ISSUE TITLE
Upstream Issues

### ISSUE THREAD

**Issue by Zendrex** [HexagonMC/BungeeCord#27]
````
WARNING [Username] -> UpstreamBridge - IOException: syscall:read(...)() failed: Connection reset by peer
INFO [Username] disconnected with: NativeIoException : syscall:read(...)() failed: Connection reset by peer
````

Several of my users are getting this issue and are unable to connect to the servers for some reason. I can confirm this is happening with this variant of bungeecord. (these clients are using modpacks on 1.7.10)

**Comment by Zendrex** [comment]
Suggest taking a look at this: https://github.com/TCPR/BungeeCord

**Comment by ghacproductions** [comment]
Can you somehow reproduce the error? Would make it a lot easier to find the problem.

**Comment by Zendrex** [comment]
This is completely random. I don't know what causes it, why it happens or how to reproduce it. There is no indepth information in the consoles or logs. Apparently sometimes resetting the players .dat file in the server save resolves it. I think it has to do with the server not sending the correct information to the client or vise versa.

**Comment by Zendrex** [comment]
Here is an error log from one of my users. NOTE: this only happens with this variant of bungee.

http://pastebin.com/uKFJHg1r

**Comment by Zendrex** [comment]
````
[11:11:40] [Client thread/INFO] [FML]: Applying holder lookups
[11:11:40] [Client thread/INFO] [FML]: Holder lookups applied
[11:11:42] [Client thread/FATAL]: Unreported exception thrown!
java.lang.IllegalArgumentException: Could not get provider type for dimension 14, does not exist
        at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148) ~[DimensionManager.class:?]
        at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302) ~[DimensionManager.class:?]
        at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160) ~[aqo.class:?]
        at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54) ~[bjf.class:?]
        at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:871) ~[bjb.class:?]
        at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32) ~[hs.class:?]
        at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13) ~[hs.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) ~[bje.class:?]
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) ~[bao.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
````

**Comment by i9hdkill** [comment]
Seems like you are using a heavily modded Forge server which is not supported.

**Comment by Zendrex** [comment]
So there are no plans for supporting modpack servers?

**Comment by Zendrex** [comment]
Thoughts I would just leave this here if you ever considered it...
https://github.com/TCPR/BungeeCord/commits?author=Yive
