### ISSUE TITLE
Spamming Error in console

### ISSUE THREAD

**Issue by GGNoPotato** [HexagonMC/BungeeCord#33]
09:53:14 [SEVERE] May 13, 2016 9:53:14 AM io.netty.channel.ChannelInitializer exceptionCaught
WARNING: Failed to initialize a channel. Closing: [id: 0x557ee6a6, /24.45.178.102:59463 => /167.114.156.51:25565]
java.lang.NoSuchMethodError: net.md_5.bungee.connection.InitialHandler.<init>(Lnet/md_5/bungee/api/ProxyServer;Lnet/md_5/bungee/api/config/ListenerInfo;)V
    at protocolsupport.protocol.CheckedInitialHandler.<init>(CheckedInitialHandler.java:12)
    at protocolsupport.injector.NettyInjector$ProxyChannelInitializer.initChannel(NettyInjector.java:31)
    at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:143)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:129)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:733)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:450)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:378)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:424)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:259)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)

**Comment by i9hdkill** [comment]
You are using an outdated bungee plugin

**Comment by GGNoPotato** [comment]
I tried with the top 5 most recent. I had the same error.

**Comment by i9hdkill** [comment]
Do you have SuperMOTD installed?

**Comment by GGNoPotato** [comment]
No I dont.

ServerListPlus-3.4.4-Bukkit-1.7.X.jar
ProtocolSupportBungee(1).jar
BungeeIPBan.jar

**Comment by i9hdkill** [comment]
ServerListPlus-3.4.4-Bukkit-1.7.X.jar should be ServerListPlus-3.4.4-UNIVERSAL

BungeeIPBan ist most likely broken and causing this issue.

**Comment by GGNoPotato** [comment]
ServerListPlus-3.4.4-UNIVERSAL
Would this work for servers running 1.7-1.9?

**Comment by i9hdkill** [comment]
yes this will work

**Comment by i9hdkill** [comment]
Closing the issue, as this is not a Bungee issue.
