### ISSUE TITLE
PingHandler IllegalStateException when pinging 1.7.10 mod server

### ISSUE THREAD

**Issue by Brian-Graham** [HexagonMC/BungeeCord#39]
There is a consistent IllegalStateException when repeatedly pinging a 1.7.10 mod server (specifically we are using Forge with Pixelmon).

```
21:30:32 [SEVERE] [Ping Handler] -> pixelmon - encountered exception
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
    at com.google.gson.Gson.fromJson(Gson.java:810)
    at com.google.gson.Gson.fromJson(Gson.java:775)
    at com.google.gson.Gson.fromJson(Gson.java:724)
    at com.google.gson.Gson.fromJson(Gson.java:696)
    at net.md_5.bungee.connection.PingHandler.handle(PingHandler.java:57)
    at net.md_5.bungee.protocol.packet.StatusResponse.handle(StatusResponse.java:35)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
    at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:189)
```

**Comment by Zartec** [comment]
Looks like the forge server isn't sending back a proper formatted json string.

I have build a version in which this line inside `net.md_5.bungee.connection.PingHandler`
[```callback.done( gson.fromJson( statusResponse.getResponse(), ServerPing.class ), null );```](https://github.com/HexagonMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/PingHandler.java#L57)
is changed to
```
try
{
    callback.done( gson.fromJson( statusResponse.getResponse(), ServerPing.class ), null );
}
catch (JsonSyntaxException e)
{
    System.err.println("Error while parsing status response:");
    System.err.println(statusResponse.getResponse());
    throw e;
}
```
This should show the malformed json string if gson is not able to parse it.

Would be nice if you can try to use this version and look again at the error.

[BungeeCord.jar.zip](https://github.com/HexagonMC/BungeeCord/files/302578/BungeeCord.jar.zip) [Antivirus](https://www.virustotal.com/de/file/a6148e88cc9931c1b5c0bec099578a7dc77d36c5d7fef9a6b189fb4915e5371a/analysis/1465304114/)
[BungeeCord.jar.tar.gz](https://github.com/HexagonMC/BungeeCord/files/302579/BungeeCord.jar.tar.gz) [Antivirus](https://www.virustotal.com/de/file/d7b9a426afeebae9a7bf602bdf39ee2f5944fd49e02a9e97d27ab74a481157ca/analysis/1465304231/)

**Comment by Brian-Graham** [comment]
I've swapped out our BungeeCord for that version. I'll respond back when the error happens again.

**Comment by Zartec** [comment]
Thanks

**Comment by Brian-Graham** [comment]
Ok the error has re-appeared, here is the exception with your debug line:
```
Error while parsing status response:
"Server is still starting! Please wait before reconnecting."
[Ping Handler] -> pixelmon - encountered exception
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at com.google.gson.Gson.fromJson(Gson.java:696)
	at net.md_5.bungee.connection.PingHandler.handle(PingHandler.java:61)
	at net.md_5.bungee.protocol.packet.StatusResponse.handle(StatusResponse.java:35)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:189)
	... 25 more
```

**Comment by ghacproductions** [comment]
Is this error still present?

**Comment by MJRLegends** [comment]
@ghacproductions yeah i still get this too

**Comment by ghacproductions** [comment]
@MJRLegends Can you provide me some recent log files, where this error occurs?

**Comment by MJRLegends** [comment]
@ghacproductions did you want the whole log or just the parts of the error ?

**Comment by MJRLegends** [comment]
Also it seems its not just your bungeecord fork that has this issue
