### ISSUE TITLE
PingHandler IllegalStateException: Not expecting PING

### ISSUE THREAD

**Issue by Brian-Graham** [HexagonMC/BungeeCord#40]
There are no indicators as to which server is being pinged / responding when this appears.
```
[/75.126.137.90:57021] <-> InitialHandler - encountered exception
java.lang.IllegalStateException: Not expecting PING
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:249)
	at net.md_5.bungee.protocol.packet.PingPacket.handle(PingPacket.java:35)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Zartec** [comment]
This is because its an exception from the HandlerBoss. At this point there is no possibility to get the server name. Only the address and port is possible.

This exception should also never be thrown in the normal protocol.

**Comment by Brian-Graham** [comment]
Is there anything on my end that I need to change or is this a problem because of 1.7 pinging (assuming you mean 1.8.x+ is the normal protocol)?
