### ISSUE TITLE
BungeeTablistPlus

### ISSUE THREAD

**Issue by Xayanix** [HexagonMC/BungeeCord#43]
```
01:01:34 [SEVERE] [nick] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:643)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:636)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:944)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:239)
	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:49)
	at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:149)
	at codecrafter47.bungeetablistplus.tablisthandler.CustomTabList18.exclude(CustomTabList18.java:186)
	at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:147)
	at codecrafter47.bungeetablistplus.ResendThread.lambda$run$0(ResendThread.java:119)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:259)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at net.md_5.bungee.protocol.DefinedPacket.writeString(DefinedPacket.java:18)
	at net.md_5.bungee.protocol.packet.PlayerListItem.write(PlayerListItem.java:92)
	at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:24)
	at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 16 more
01:01:34 [INFO] [Filoo7331] disconnected with: §fEncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToByteEncoder:125

```

Error when using BungeeTablistPlus plugin.

**Comment by i9hdkill** [comment]
What version of btlp are you using?

**Comment by Xayanix** [comment]
Yes, it is.

**Comment by Xayanix** [comment]
I have that error only on that BungeeCord, on default 1.7-1.8 its not happening.

**Comment by i9hdkill** [comment]
What's the build number of your HexaCord Version?

**Comment by Xayanix** [comment]
Never mind, disabled showing tablist on 1.8+ and its fine.
