### ISSUE TITLE
[Bug] Kicks players to fallback/default server when they execute some commands..

### ISSUE THREAD

**Issue by dig** [HexagonMC/BungeeCord#61]
Hey,

I am getting kicked when I do a command from a plugin, I get kicked to the fallback/default server. Heres the error which happens when I get kicked,

```
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
    at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:36)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:883)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:389)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by i9hdkill** [comment]
Hi,
make sure all your bungee plugins are updated to 1.10.
What Chatplugin are you using on that specific server?

**Comment by DigitalSniperz** [comment]
Its a /item plugin (to spawn in items) and it was made by me. It used to work on a bungeecord 1.7.10 we used to use but ever since I switched to your bungeecord it now kicks you.

**Comment by i9hdkill** [comment]
What is your spigot version? Does this happen on the original Bungee 1.8-1.10 aswell?

**Comment by DigitalSniperz** [comment]
We use 1.7.10 thermos on each servers, we are a modpack network. On the old 1.7.10 bungeecord, the command was not kicking the player. We only changed the bungeecord to your one and now its kicking the player.
