### ISSUE TITLE
Minecraft Sessions, Connection Errors

### ISSUE THREAD

**Issue by CleansedYT** [HexagonMC/BungeeCord#68]
This has  been happening periodically ever since I updated bungeecord to the latest version. MC sessions weren't down when this error occurred. 

19:26:40 [SEVERE] Error authenticating Cleansed with minecraft.net
io.netty.channel.ConnectTimeoutException: connection timed out: sessionserver.mojang.com/54.230.33.218:443
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe$1.run(AbstractEpollStreamChannel.java:713)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
    at java.lang.Thread.run(Unknown Source)

**Comment by i9hdkill** [comment]
DNS issue with your dedicated server.
