### ISSUE TITLE
1.9 Server freeze on join

### ISSUE THREAD

**Issue by Tom-III** [HexagonMC/BungeeCord#7]
Hexagon BungeeCord no plugins and Spigot 1.9 with no plugins and minecraft 1.9 with no mods.  When I connect I get kicked or freeze at Downloading Terrain with this on the server console:

```
23:22:41 [INFO] [/127.0.0.1:54074] <-> InitialHandler has connected
23:25:20 [INFO] [/127.0.0.1:54228] <-> InitialHandler has connected
23:25:21 [INFO] [squirrelmail] <-> InitialHandler has connected
23:25:23 [INFO] [squirrelmail] <-> ServerConnector [lobby] has connected
23:25:23 [WARNING] [squirrelmail] <-> DownstreamBridge <-> [lobby] - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.SetCompression 70 Protocol GAME Direction TO_CLIENT
23:25:23 [SEVERE] io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.SetCompression 70 Protocol GAME Direction TO_CLIENT
23:25:23 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
23:25:23 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
23:25:23 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
23:25:23 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
23:25:23 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
23:25:23 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
23:25:23 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
23:25:23 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
23:25:23 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
23:25:23 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
23:25:23 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
23:25:23 [SEVERE] 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
23:25:23 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
23:25:23 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
23:25:23 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
23:25:23 [SEVERE] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
23:25:23 [SEVERE] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
23:25:23 [SEVERE] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
23:25:23 [SEVERE] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
23:25:23 [SEVERE] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
23:25:23 [SEVERE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
23:25:23 [SEVERE] 	at java.lang.Thread.run(Unknown Source)
23:25:23 [SEVERE] Caused by: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.SetCompression 70 Protocol GAME Direction TO_CLIENT
23:25:23 [SEVERE] 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:37)
23:25:23 [SEVERE] 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
23:25:23 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
23:25:23 [SEVERE] 	... 21 more
23:25:23 [INFO] [squirrelmail] disconnected with: §fDecoderException : net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.SetCompression 70 Protocol GAME Direction TO_CLIENT @ io.netty.handler.codec.MessageToMessageDecoder:99
23:25:23 [INFO] [squirrelmail] disconnected with: §f[Proxy] Lost connection to server.
23:25:23 [INFO] [squirrelmail] <-> DownstreamBridge <-> [lobby] has disconnected
23:25:23 [INFO] [squirrelmail] -> UpstreamBridge has disconnected
```

**Comment by ghacproductions** [comment]
What version of BungeeCord are you using? Try with the latest one.

**Comment by Tom-III** [comment]
Downloaded v26, all issues fixed, thanks for such a great system!

**Comment by ghacproductions** [comment]
Thanks.
