### ISSUE TITLE
The client crashes When a thaumcraft server switching to another thaumcraft server  with bungeecord.

### ISSUE THREAD

**Issue by ccxufo** [HexagonMC/BungeeCord#85]
when a player Hold a  wang(installed foucus) switch to another server,the client would crash.  
it only happen when thaumcraft server switch to thaumcraft,but vanilla switch to thaumcraft is not be.
there is the crash-reported.  
It just like mod conflict.

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 16-10-6 下午3:26
Description: Rendering item

java.lang.ClassCastException: com.teammetallurgy.metallurgy.tools.Hoe cannot be cast to thaumcraft.api.wands.ItemFocusBasic
    at thaumcraft.common.items.wands.ItemWandCasting.getFocus(ItemWandCasting.java:433)
    at thaumcraft.client.renderers.models.gear.ModelWand.render(ModelWand.java:136)
    at thaumcraft.client.renderers.item.ItemWandRenderer.renderItem(ItemWandRenderer.java:133)
    at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
    at net.minecraft.client.gui.GuiIngame.func_73832_a(GuiIngame.java:955)
    at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:206)
    at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1328)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at thaumcraft.common.items.wands.ItemWandCasting.getFocus(ItemWandCasting.java:433)
    at thaumcraft.client.renderers.models.gear.ModelWand.render(ModelWand.java:136)
    at thaumcraft.client.renderers.item.ItemWandRenderer.renderItem(ItemWandRenderer.java:133)
    at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)

-- Item being rendered --
Details:
    Item Type: thaumcraft.common.items.wands.ItemWandCasting@23295bac
    Item Aux: 54
    Item NBT: {aqua:10000,terra:10000,ignis:9559,cap:"thaumium",rod:"silverwood",focus:{id:4451s,Count:1b,Damage:0s,},ordo:10000,perditio:10000,aer:10000,}
    Item Foil: false
Stacktrace:
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
    at net.minecraft.client.gui.GuiIngame.func_73832_a(GuiIngame.java:955)
    at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:206)
    at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['CCU_X'/558, l='MpServer', x=59.66, y=71.62, z=300.20]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (48,64,256), Chunk: (at 0,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 44338 game time, 44338 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 39 total; [EntityCow['牛'/65, l='MpServer', x=22.84, y=70.00, z=245.06], EntityClientPlayerMP['CCU_X'/558, l='MpServer', x=59.66, y=71.62, z=300.20], EntityCreeper['爬行者'/521, l='MpServer', x=-2.13, y=72.00, z=274.75], EntityClientPlayerMP['CCU_X'/558, l='MpServer', x=8.50, y=66.62, z=8.50], EntityCreeper['爬行者'/270, l='MpServer', x=88.50, y=16.00, z=252.50], EntityCreeper['爬行者'/272, l='MpServer', x=87.34, y=16.00, z=255.34], EntityZombie['僵尸'/85, l='MpServer', x=62.56, y=14.00, z=266.56], EntitySpider['蜘蛛'/472, l='MpServer', x=9.38, y=70.00, z=246.84], EntityCow['牛'/98, l='MpServer', x=69.81, y=73.00, z=239.13], EntityWizzrobe['威兹长袍'/548, l='MpServer', x=42.31, y=20.00, z=325.91], EntitySkeleton['骷髅'/612, l='MpServer', x=108.50, y=63.00, z=335.50], EntityKeese['蝙蝠'/101, l='MpServer', x=73.69, y=55.10, z=250.38], EntityCow['牛'/41, l='MpServer', x=-1.69, y=70.00, z=241.31], EntityCow['牛'/42, l='MpServer', x=-2.53, y=70.00, z=243.28], EntityCow['牛'/106, l='MpServer', x=82.66, y=68.00, z=239.75], EntityBat['蝙蝠'/555, l='MpServer', x=56.50, y=42.10, z=296.75], EntityPig['猪'/43, l='MpServer', x=-4.50, y=71.00, z=320.50], EntityCow['牛'/109, l='MpServer', x=80.69, y=64.00, z=266.50], EntityCreeper['爬行者'/621, l='MpServer', x=87.50, y=25.00, z=335.50], EntityCreeper['爬行者'/622, l='MpServer', x=89.46, y=26.00, z=335.53], EntityPig['猪'/111, l='MpServer', x=88.50, y=84.00, z=362.50], EntityCreeper['爬行者'/623, l='MpServer', x=89.59, y=25.80, z=334.67], EntityCreeper['爬行者'/624, l='MpServer', x=91.66, y=25.00, z=334.63], EntityPig['猪'/113, l='MpServer', x=92.50, y=84.00, z=360.50], EntityCreeper['爬行者'/625, l='MpServer', x=90.66, y=25.00, z=332.16], EntityZombie['僵尸'/627, l='MpServer', x=77.50, y=49.00, z=243.50], EntityCreeper['爬行者'/628, l='MpServer', x=73.50, y=49.00, z=241.50], EntityCreeper['爬行者'/629, l='MpServer', x=78.50, y=48.92, z=244.50], EntityCow['牛'/54, l='MpServer', x=4.25, y=70.00, z=238.19], EntityCow['牛'/55, l='MpServer', x=-3.03, y=70.00, z=258.94], EntityCow['牛'/120, l='MpServer', x=104.50, y=64.00, z=261.50], EntityCow['牛'/121, l='MpServer', x=106.47, y=66.00, z=263.50], EntityCow['牛'/122, l='MpServer', x=106.50, y=66.00, z=261.50], EntityZombie['僵尸'/58, l='MpServer', x=10.50, y=72.00, z=272.50], EntityCow['牛'/123, l='MpServer', x=107.53, y=67.00, z=263.50], EntityPig['猪'/59, l='MpServer', x=5.06, y=70.00, z=312.09], EntityPig['猪'/60, l='MpServer', x=3.59, y=70.00, z=316.56], EntityPig['猪'/61, l='MpServer', x=0.75, y=77.00, z=319.50], EntityCow['牛'/62, l='MpServer', x=20.81, y=68.00, z=239.19]]
    Retry entities: 0 total; []
    Server brand: HexaCord (git:BungeeCord-Bootstrap:1.10-SNAPSHOT:4271c73:unknown) <- thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_102, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 70683368 bytes (67 MB) / 396886016 bytes (378 MB) up to 481296384 bytes (459 MB)
    JVM Flags: 1 total; -Xmx516M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.85.1240 Minecraft Forge 10.13.2.1240 Optifine OptiFine_1.7.10_HD_U_C1 20 mods loaded, 20 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.85.1240} [Forge Mod Loader](forge-1.7.10-10.13.2.1240.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.2.1240} [Minecraft Forge](forge-1.7.10-10.13.2.1240.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    InputFix{1.7.x-v4} [InputFix](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    zeldaswordskills{1.7.10-0.2.0} [Zelda Sword Skills](1.7.10DCore-zeldaswordskills-beta-0.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AntiCheat3{AntiCheat 3 Mod} [AntiCheat 3 Mod](ANTI.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    XaeroBetterPvP{1.9.1.1} [Better PVP Mod](BetterPvP1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BeeSwitch{1.0} [BeeSwitch](cross.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FastCraft{1.9} [FastCraft](fastcraft-1.9fps.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Thaumcraft{4.2.3.5} [Thaumcraft](M-Thaumcraft-1.7.10-4.2.3.5-SaraFix-a0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MetallurgyCore{4.0.4} [Metallurgy Core](Metallurgy-Core1.7.10-.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct{1.7.10-1.7.0.build665} [Tinkers' Construct](TConstruct-1.7.10-1.7.0d2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Metallurgy{4.0.6} [Metallurgy 4](Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    customnpcs{1.7.10d} [CustomNpcs](NPC.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    craftguide{1.6.8.1} [CraftGuide](可选安装CraftGuide-1.6.8.15D.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DamageIndicatorsMod{3.2.0} [Damage Indicators](可选安装DamageIndicators.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mobends{v0.15 for 1.7.10} [Mo' Bends](可选安装mobends-v0.19forMC-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    UnicodeFontFixer{1.0.8} [UnicodeFontFixer](可选安装UnicodeFontFixer-1.0.8-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    Launched Version: 1.7.10-Forge10.13.2.1240
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 20.19.15.4360, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [服务器推荐资源包.zip]
Current Language: 简体中文 (中国)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Arobcher** [comment]
`All players: 1 total; [EntityClientPlayerMP['CCU_X'/558, l='MpServer', x=59.66, y=71.62, z=300.20]]
Chunk stats: MultiplayerChunkCache: 441, 441
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options: 
Level spawn location: World: (48,64,256), Chunk: (at 0,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 44338 game time, 44338 day time
Level dimension: 0
Try to fix this chunk of coordinates`

**Comment by ccxufo** [comment]
I am sorry for my broken English.
I have try to delete the chunk ,but I still have this problem.   
All is okay when I switch to server without BungeeCord. I'm in doubt is caused by thaumcraft.
All is okay when I only install thaumcraft mod in server,but I add others mod in to server , client would go crash.  

> ---- Minecraft Crash Report ----
// You're mean.

Time: 16-10-7 下午1:13
Description: Unexpected error

java.lang.ClassCastException: zeldaswordskills.item.ItemBomb cannot be cast to thaumcraft.api.wands.ItemFocusBasic
	at thaumcraft.common.items.wands.ItemWandCasting.getFocus(ItemWandCasting.java:433)
	at thaumcraft.client.renderers.models.gear.ModelWand.render(ModelWand.java:136)
	at thaumcraft.client.renderers.item.ItemWandRenderer.renderItem(ItemWandRenderer.java:133)
	at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:220)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:499)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at thaumcraft.common.items.wands.ItemWandCasting.getFocus(ItemWandCasting.java:433)
	at thaumcraft.client.renderers.models.gear.ModelWand.render(ModelWand.java:136)
	at thaumcraft.client.renderers.item.ItemWandRenderer.renderItem(ItemWandRenderer.java:133)
	at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:220)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:499)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)

-- Affected level --
Details:
	Level name: MpServer

I don't konw whether you care about mods.This is my situation,I don't know if I can find a solution.

**Comment by thomas15v** [comment]
The problem is caused in the render class for thaumcraft wands. The only solution I could think of is sending a packet to clear the inventory client side before switching servers.

**Comment by Eufranio** [comment]
There is a issue with Baubles working (client-side) when switching servers. The effects like jump boost and speed still working in the client side, and players can abuse.

**Comment by i9hdkill** [comment]
Could you pls retest with Buildv99?

**Comment by ccxufo** [comment]
The problem still in Buildv99, when I switch to another server, my client would carsh.
