### ISSUE TITLE
ProtocolSupport for Bungee

### ISSUE THREAD

**Issue by Zilacon** [HexagonMC/BungeeCord#86]
I am attempting to use ProtocolSupportBungee for HexagonBungee to run 1 bungeecord and 1 hub connected to 1.5.2, 1.6.4, 1.7.10 modpack servers with a 1.10.2 MC hub/game server.

The plugin works flawlessly standalone on spigot 1.10.2 for 1.5.2-1.10.2 however with 1.6.4 and 1.5.2 using HexagonBungee and the ProtocolSupportBungee plugin i get this:

```
io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException: direct buffer
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:111)
    at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.channelRead(InitialPacketDecoder.java:90)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:972)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:386)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: direct buffer
    at io.netty.buffer.UnpooledUnsafeDirectByteBuf.array(UnpooledUnsafeDirectByteBuf.java:203)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDataSerializer.readString(PacketDataSerializer.java:12)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.packets.HandshakePacket.read(HandshakePacket.java:31)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.reader.PacketReader.readDefinedPacket(PacketReader.java:111)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.reader.PacketReader.readPacket(PacketReader.java:42)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:41)
    at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:17)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    ... 22 more
```

![screenshot_9](https://cloud.githubusercontent.com/assets/3002248/19234511/ff738dd8-8ea0-11e6-971c-00487c443c35.png)
![screenshot_10](https://cloud.githubusercontent.com/assets/3002248/19234510/ff6d5fb2-8ea0-11e6-99ce-f629a5f1b8b0.png)

Any help with this would be great as im trying to make it so 1 IP for my network connects to all of my servers instead of having a giant list of IP's for every modpack i host.

**Comment by KatsuroKurosaki** [comment]
I also give my +1 on this.

Because the official md_5's BungeeCord doesn't support 1.7 clients, although I can connect using 1.6 and 1.5, and ProtocolSupport developer links to this BungeeCord taht supports 1.7 but I neither can't connect using 1.6 nor 1.5...
ProtocolSupport dev page on Spigot that tells us how to get 1.7 support: https://www.spigotmc.org/resources/protocolsupportbungee.8733/

Regards

**Comment by i9hdkill** [comment]
If you wanna use 1.6 and below, use the original 1.8-1.10 BungeeCord from md_5

**Comment by KatsuroKurosaki** [comment]
But md_5's BungeeCord has dropped 1.7 support.

**Comment by i9hdkill** [comment]
Just saw that ProtocolSupport dropped 1.7 support aswell.
You might try updating to the latest Protocolsupport and ProtocolsupportBungee builds and try again.

If the issue persists, contact the author of Protocolsupport. He might be able to fix it.

**Comment by KatsuroKurosaki** [comment]
Actually using HexagonMC/Bungee and latest ProtocolSupport dev build, all works fine, until 2 days after, the console gets spammed with a lot of messages about not enough memory for Netty. When this happened, I raised -Xmx 2500M to -Xmx 4000M and still got the errors...
Unluckily, ProtocolSupport developer abandoned the project, so... I'll stick with HexagonMC's bungee, I have a good amount of 1.7 and 1.8 players (more than 50% of the players), and I'll wait until drops 30% and drop support for 1.7 and 1.8

**Comment by i9hdkill** [comment]
Quite easy, remove ProtocolSupportBungee and all should be finde. Only downside: No support for 1.5 and 1.6.
Who the hell plays on 1.5 and 1.6?

**Comment by KatsuroKurosaki** [comment]
I still have players who played 1.5 on my server. A huge DAFUQ, but, life goes on, dude, 1.7 should not be a big deal for them. A 1.10.2 Spigot server, and joining with 1.5... yeah time to move on.

**Comment by i9hdkill** [comment]
Yep. Change the outdated version kickmessage to like: Please update to 1.10.2 or at least 1.7.10 and you should be fine.

**Comment by KatsuroKurosaki** [comment]
Already did, and having an average of 200 online players, 1 or 2% being 1.5-1.6 won't make a big deal.
